language: cpp
compiler: g++
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
before_install:
  - sudo apt-get install cmake
install:
  - git clone https://github.com/samtools/htslib.git
  - pushd htslib && autoheader && autoconf && ./configure --prefix=/usr && make && sudo make install && popd