#!/usr/bin/perl -w

use strict;

my ($out,$index) = @ARGV;

my @ids = ();
my @mpus = ();
open(IN,$index) || die "Cannot open file\n";
while(<IN>) {
    next if ( /^#/ );
    my @F = split;
    if ( $#F == 1 ) {
	push(@ids,$F[0]);
	push(@mpus,$F[1]);
    }
    elsif ( $#F == 5 ) {
	push(@ids,$F[1]);
	push(@mpus,$F[$#F]);
    }
    else {
	die "Expected number of columns are 2 or 5\n";
    }
}
close IN;

my @fmixs = ();
my @cmixs = ();
for(my $i=0; $i < @ids; ++$i) {
    open(IN,"$out.$ids[$i].selfSM") || die "Cannot open file\n";
    my $line = <IN>;
    my @F = split(/[\t\r\n]/,<IN>);
    push(@fmixs,$F[6]);
    push(@cmixs,$F[11]);
    close IN;
}

open(OUT,">$out.ped") || die "Cannot open file\n";
print OUT "#FAM_ID\tIND_ID\tFAT_ID\tMOT_ID\tSEX\tMPU\tFREEMIX\tCHIPMIX\n";
for(my $i=0; $i < @ids; ++$i) {
    print OUT "$ids[$i]\t$ids[$i]\t0\t0\t0\t$mpus[$i]\t$fmixs[$i]\t$cmixs[$i]\n";
}
close OUT;
